# -*- coding: utf-8 -*-
"""Copy of notebook "HW2_3_python_basics.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsG5fPnw78kvvPHP7uq0Tfj5Aqotlpb0

# Python Bootcamp: Assignment 3 [100 points]

This week we will start writing some code! This assignment is designed to be a crash-course to get you up to speed on the level of Python you will need to know in order to do the remainder of the assignments. It's easiest to learn by doing, so please start early so we can help you get on board. You want to spend the semester focusing on the crowdsourcing and machine learning, not the indenting and semicoloning.

Before you do anything save a copy of this file in Drive (found in File) and work on that one.

## 1. Working with Lists [15 points]

1. **[5 points]** Consider the function `extract_and_apply(l, p, f)` shown below, which extracts the elements of a list `l` satisfying a boolean predicate `p`, applies a function f to each such element, and returns the result.

  Rewrite `extract_and_apply(l, p, f)` in one line using a list comprehension.
"""

def extract_and_apply(l, p, f):
     result = []
     for x in l:
         if p(x):
             result.append(f(x))
     return result

def extract_and_apply(l, p, f):
  res = [x for x in l if p(x)]
  return res

l = [1, 2, 3, 4]
p = lambda x: x % 2 == 0
f = lambda x: x
extract_and_apply(l, p, f)

# # Example:
# l = [1, 2, 3, 4]
# p = lambda x: x % 2 == 0
# f = lambda x: x
# extract_and_apply(l, p, f)

# # Expected output:
# # [2, 4]

"""2. **[5 points]** Write a function `concatenate(seqs)` that returns a list containing the concatenation of the elements of the input sequences. Your implementation should consist of a single list comprehension, and should not exceed one line.


"""

def concatenate(seqs):
  res = [x for i in seqs for x in i]
  return res

concatenate([[1, 2], [3, 4]])
concatenate(["abc", (0, [0])])

# # Example:
# concatenate([[1, 2], [3, 4]])

# # Expected output:
# # [1, 2, 3, 4]

# # Example:
# concatenate(["abc", (0, [0])])

# # Expected output:
# # ['a', 'b', 'c', 0, [0]]

"""3. **[5 points]** Write a function `transpose(matrix)` that returns the transpose of the input matrix, which is represented as a list of lists. Recall that the transpose of a matrix is obtained by swapping its rows with its columns. More concretely, the equality `matrix[i][j] == transpose(matrix)[j][i`] should hold for all valid indices `i` and `j`. You may assume that the input matrix is well-formed, i.e., that each row is of equal length. You may further assume that the input matrix is non-empty. Your function should not modify the input."""

def transpose(matrix):
  m, n = len(matrix), len(matrix[0])
  return [[matrix[i][j] for i in range(m)] for j in range(n)]
transpose([[1, 2], [3, 4], [5, 6]])

# # Example:
# transpose([[1, 2, 3]])

# # Expected output:
# # [[1], [2], [3]]

# # Example:
# transpose([[1, 2], [3, 4], [5, 6]])

# # Expected output:
# # [[1, 3, 5], [2, 4, 6]]

"""## 2. Sequence Slicing [9 points]

The functions in this section should be implemented using sequence slices. Recall that the slice parameters take on sensible default values when omitted. In some cases, it may be necessary to use the optional third parameter to specify a step size.

1. **[3 points]** Write a function `copy(seq)` that returns a new sequence containing the same elements as the input sequence.
"""

def copy(seq):
    res = seq[:]
    return res
x = [0, 0, 0]
y = copy(x)
print(x, y)

x[0] = 1
print(x, y)

# # Example:
# copy("abc")

# # Expected output:
# # 'abc'

# # Example:
# copy((1, 2, 3))

# # Expected output:
# #  (1, 2, 3)

# # Example:
# x = [0, 0, 0]
# y = copy(x)
# print(x, y)

# x[0] = 1
# print(x, y)

# # Expected output:
# # [0, 0, 0] [0, 0, 0]
# # [1, 0, 0] [0, 0, 0]

"""2. **[3 points]** Write a function `all_but_last(seq)` that returns a new sequence containing all but the last element of the input sequence. If the input sequence is empty, a new empty sequence of the same type should be returned."""

def all_but_last(seq):
  res = seq[:-1]
  return res
all_but_last((1, 2, 3))

# # Example:
# all_but_last("abc")

# # Expected output:
# # 'ab'

# # Example:
# all_but_last((1, 2, 3))

# # Expected output:
# # (1, 2)

# # Example:
# all_but_last("")

# # Expected output:
# # ''

# # Example:
# all_but_last([])

# # Expected output:
# # []

"""3. **[3 points]** Write a function `every_other(seq)` that returns a new sequence containing every other element of the input sequence, starting with the first. This function can be written in one line using the optional third parameter of the slice notation."""

def every_other(seq):
  res = seq[::2]
  return res
every_other([1, 2, 3, 4, 5])

# # Example:
# every_other([1, 2, 3, 4, 5])

# # Expected output:
# # [1, 3, 5]

# # Example:
# every_other("abcde")

# # Expected output:
# # 'ace'

# # Example:
# every_other([1, 2, 3, 4, 5, 6])

# # Expected output:
# # [1, 3, 5]

# # Example:
# every_other("abcdef")

# # Expected output:
# # 'ace'

"""## 3. Combinatorial Algorithms [12 points]

The functions in this section should be implemented as generators. You may generate the output in any order you find convenient, as long as the correct elements are produced. However, in some cases, you may find that the order of the example output hints at a possible implementation.

Although generators in Python can be used in a variety of ways, you will not need to use any of their more sophisticated features here. Simply keep in mind that where you might normally return a list of elements, you should instead yield the individual elements.

Since the contents of a generator cannot be viewed without employing some form of iteration, we wrap all function calls in this section’s examples with the list function for convenience.

1. **[6 points]** The prefixes of a sequence include the empty sequence, the first element, the first two elements, etc., up to and including the full sequence itself. Similarly, the suffixes of a sequence include the empty sequence, the last element, the last two elements, etc., up to and including the full sequence itself. Write a pair of functions `prefixes(seq)` and `suffixes(seq)` that yield all prefixes and suffixes of the input sequence.
"""

def prefixes(seq):
    res = [seq[0:i]for i in range(len(seq)+1)]
    return res
list(prefixes([1, 2, 3]))
list(prefixes("abc"))

def suffixes(seq):
    res = [seq[i:]for i in range(len(seq)+1)]
    return res
list(suffixes([1, 2, 3]))
list(suffixes("abc"))

# # Example:
# list(prefixes([1, 2, 3]))

# # Expected output:
# # [[], [1], [1, 2], [1, 2, 3]]

# # Example:
# list(suffixes([1, 2, 3]))

# # Expected output:
# # [[1, 2, 3], [2, 3], [3], []]

# # Example:
# list(prefixes("abc"))

# # Expected output:
# # ['', 'a', 'ab', 'abc']

# # Example:
# list(suffixes("abc"))

# # Expected output:
# # ['abc', 'bc', 'c', '']

"""2. **[6 points]** Write a function `slices(seq)` that yields all non-empty slices of the input sequence."""

def slices(seq):
  res = [seq[i:j]for i in range(len(seq)+1) for j in range (len(seq)+1) if (seq[i:j])]
  return res
list(slices([1, 2, 3]))
list(slices("abc"))

# # Example:
# list(slices([1, 2, 3]))

# # Expected output:
# # [[1], [1, 2], [1, 2, 3], [2], [2, 3], [3]]

# # Example:
# list(slices("abc"))

# # Expected output:
# # ['a', 'ab', 'abc', 'b', 'bc', 'c']

"""## 4. Text Processing [20 points]

1. **[5 points]** A common preprocessing step in many natural language processing tasks is text normalization, wherein words are converted to lowercase, extraneous whitespace is removed, etc. Write a function `normalize(text)` that returns a normalized version of the input string, in which all words have been converted to lowercase and are separated by a single space. No leading or trailing whitespace should be present in the output.
"""

def normalize(text):
  text = text.lower()
  return ' '.join(text.split())
normalize("   EXTRA   SPACE   ")

# # Example:
# normalize("This is an example.")

# # Expected output:
# # 'this is an example.'

# # Example:
# normalize("   EXTRA   SPACE   ")

# # Expected output:
# # 'extra space'

"""2. **[5 points]** Write a function `no_vowels(text)` that removes all vowels from the input string and returns the result. For the purposes of this problem, the letter ‘y’ is not considered to be a vowel.


"""

def no_vowels(text):
  vow = 'aeiouAEIOU'
  return ''.join(i for i in text if i not in vow)
no_vowels("This Is An Example.")

# # Example:
# no_vowels("This Is An Example.")

# # Expected output:
# # 'Ths s n xmpl.'

# # Example:
# no_vowels("We love Python!")

# # Expected output:
# # 'W lv Pythn!'

"""3. **[5 points]** Write a function `digits_to_words(text)` that extracts all digits from the input string, spells them out as lowercase English words, and returns a new string in which they are each separated by a single space. If the input string contains no digits, then an empty string should be returned."""

def digits_to_words(text):
  d = {'0':'zero', '1': 'one', '2':'two', '3':'three', '4':'four', '5':'five', '6':'six', '7':'seven', '8':'eight', '9':'nine' }
  res = ''.join(i for i in text if i in d)
  result = ' '.join(d[i] for i in res)
  return result
digits_to_words("Zip Code: 19104")

# # Example:
# digits_to_words("Zip Code: 19104")

# # Expected output:
# # 'one nine one zero four'

# # Example:
# digits_to_words("Pi is 3.1415...")

# # Expected output:
# # 'three one four one five'

"""4. **[5 points]** Although there exist many naming conventions in computer programming, two of them are particularly widespread. In the first, words in a variable name are separated using underscores. In the second, words in a variable name are written in mixed case, and are strung together without a delimiter. By mixed case, we mean that the first word is written in lowercase, and that subsequent words have a capital first letter. Write a function `to_mixed_case(name)` that converts a variable `name` from the former convention to the latter. Leading and trailing underscores should be ignored. If the variable name consists solely of underscores, then an empty string should be returned.


"""

def to_mixed_case(name):
    name = name.strip('_').lower()
    x = name.split('_')
    return x[0]+''.join(i.capitalize() for i in x[1:])
to_mixed_case("__EXAMPLE__NAME__")

# # Example:
# to_mixed_case("to_mixed_case")

# # Expected output:
# # 'toMixedCase'

# # Example:
# to_mixed_case("__EXAMPLE__NAME__")

# # Expected output:
# # 'exampleName'

"""## 5. DataFrames [44 points]
In this section you'll get a feel for pandas' DataFrames a datastructure similar to SQL tables that can directly read lists and csvs and supports a number of optimized operations.

### 5.1 Manipulating a csv [30 points]
"""

# first we'll import pandas
import pandas as pd

"""1. **[2 points]** In the method `read_file` create a dataframe from the given csv file."""

# hint: look at the pandas method read_csv
def read_file(file):
  df = pd.read_csv(file)
  return df

df = read_file('batch.csv')

"""batch.csv is a csv of the results from a batch of HITs on MTurk. With it you can see worker Ids, their answers to each question, as well as their accept and submit times.

Comment the cells below out before you submit.
"""

# you can also get a smaller glimpse with
display (df.head())

#Unnamed: 0.1	Unnamed: 0	HITId	WorkerId	Answer	SubmitTime	AutoApprovalTime	ApprovalTime	AcceptTime	AssignmentStatus	...	MaxAssignments	Reward	AutoApprovalDelayInSeconds	Expiration	AssignmentDurationInSeconds	QualificationRequirements	HITReviewStatus	NumberOfAssignmentsPending	NumberOfAssignmentsAvailable	NumberOfAssignmentsCompleted
#0	0	0	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU	AVBRJBJONL47I	<?xml version="1.0" encoding="ASCII"?><Questio...	2020-02-06 23:25:41	2020-02-09 23:25:41-05:00	2020-02-09 23:25:46-05:00	2020-02-06 23:22:13	Approved	...	7	0.65	259200	2020-02-17 16:01:12-05:00	5400	[{'QualificationTypeId': '3EEL9D2EGEGJTS4ZDH30...	NotReviewed	0	3	0
#1	1	1	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU	A1CY7IOJ9YH136	<?xml version="1.0" encoding="ASCII"?><Questio...	2020-02-06 01:34:37	2020-02-09 01:34:37-05:00	2020-02-09 01:34:46-05:00	2020-02-06 01:27:28	Approved	...	7	0.65	259200	2020-02-17 16:01:12-05:00	5400	[{'QualificationTypeId': '3EEL9D2EGEGJTS4ZDH30...	NotReviewed	0	3	0
#2	2	2	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU	A2C84POENS2UNY	<?xml version="1.0" encoding="ASCII"?><Questio...	2020-02-04 10:59:35	2020-02-07 10:59:35-05:00	2020-02-07 11:00:23-05:00	2020-02-04 10:25:54	Approved	...	7	0.65	259200	2020-02-17 16:01:12-05:00	5400	[{'QualificationTypeId': '3EEL9D2EGEGJTS4ZDH30...	NotReviewed	0	3	0
#3	3	3	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU	A98E8M4QLI9RS	<?xml version="1.0" encoding="ASCII"?><Questio...	2020-02-04 07:07:59	2020-02-07 07:07:59-05:00	2020-02-07 07:08:23-05:00	2020-02-04 07:03:48	Approved	...	7	0.65	259200	2020-02-17 16:01:12-05:00	5400	[{'QualificationTypeId': '3EEL9D2EGEGJTS4ZDH30...	NotReviewed	0	3	0
#4	4	4	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU	AY7WPVKHVNBLG	<?xml version="1.0" encoding="ASCII"?><Questio...	2020-02-03 18:20:08	2020-02-06 18:20:08-05:00	2020-02-06 18:20:23-05:00	2020-02-03 18:13:47	Approved	...	7	0.65	259200	2020-02-17 16:01:12-05:00	5400	[{'QualificationTypeId': '3EEL9D2EGEGJTS4ZDH30...	NotReviewed	0	3	0
#5 rows × 92 columns

# or just the columns with
display (df.columns)

#Index(['Unnamed: 0.1', 'Unnamed: 0', 'HITId', 'WorkerId', 'Answer',
      #  'SubmitTime', 'AutoApprovalTime', 'ApprovalTime', 'AcceptTime',
      #  'AssignmentStatus', 'AssignmentId', '1.BREAKDOWN', '1.NOT BREAKDOWN',
      #  '1.POSSIBLE BREAKDOWN', '2.BREAKDOWN', '2.NOT BREAKDOWN',
      #  '2.POSSIBLE BREAKDOWN', '3.BREAKDOWN', '3.NOT BREAKDOWN',
      #  '3.POSSIBLE BREAKDOWN', '4.BREAKDOWN', '4.NOT BREAKDOWN',
      #  '4.POSSIBLE BREAKDOWN', '5.BREAKDOWN', '5.NOT BREAKDOWN',
      #  '5.POSSIBLE BREAKDOWN', '6.BREAKDOWN', '6.NOT BREAKDOWN',
      #  '6.POSSIBLE BREAKDOWN', '7.BREAKDOWN', '7.NOT BREAKDOWN',
      #  '7.POSSIBLE BREAKDOWN', '8.BREAKDOWN', '8.NOT BREAKDOWN',
      #  '8.POSSIBLE BREAKDOWN', '9.BREAKDOWN', '9.NOT BREAKDOWN',
      #  '9.POSSIBLE BREAKDOWN', '10.BREAKDOWN', '10.NOT BREAKDOWN',
      #  '10.POSSIBLE BREAKDOWN', '11.BREAKDOWN', '11.NOT BREAKDOWN',
      #  '11.POSSIBLE BREAKDOWN', '12.BREAKDOWN', '12.NOT BREAKDOWN',
      #  '12.POSSIBLE BREAKDOWN', '13.BREAKDOWN', '13.NOT BREAKDOWN',
      #  '13.POSSIBLE BREAKDOWN', '14.BREAKDOWN', '14.NOT BREAKDOWN',
      #  '14.POSSIBLE BREAKDOWN', '15.BREAKDOWN', '15.NOT BREAKDOWN',
      #  '15.POSSIBLE BREAKDOWN', '16.BREAKDOWN', '16.NOT BREAKDOWN',
      #  '16.POSSIBLE BREAKDOWN', '17.BREAKDOWN', '17.NOT BREAKDOWN',
      #  '17.POSSIBLE BREAKDOWN', '18.BREAKDOWN', '18.NOT BREAKDOWN',
      #  '18.POSSIBLE BREAKDOWN', '19.BREAKDOWN', '19.NOT BREAKDOWN',
      #  '19.POSSIBLE BREAKDOWN', '20.BREAKDOWN', '20.NOT BREAKDOWN',
      #  '20.POSSIBLE BREAKDOWN', '21.BREAKDOWN', '21.NOT BREAKDOWN',
      #  '21.POSSIBLE BREAKDOWN', 'HITTypeId', 'HITGroupId', 'CreationTime',
      #  'Title', 'Description', 'Question', 'Keywords', 'HITStatus',
      #  'MaxAssignments', 'Reward', 'AutoApprovalDelayInSeconds', 'Expiration',
      #  'AssignmentDurationInSeconds', 'QualificationRequirements',
      #  'HITReviewStatus', 'NumberOfAssignmentsPending',
      #  'NumberOfAssignmentsAvailable', 'NumberOfAssignmentsCompleted'],
      # dtype='object')

# a slice of a dataframe is called a series. for example:
display (df['HITId'])

# 	HITId
# 0	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU
# 1	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU
# 2	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU
# 3	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU
# 4	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU
# 5	3L55D8AUFAVVNBWWC4GRK7QKRM6CYU
# 6	3WRBLBQ2GR6B7SGG6I11I6HFD1J0GR
# 7	3WRBLBQ2GR6B7SGG6I11I6HFD1J0GR
# 8	3WRBLBQ2GR6B7SGG6I11I6HFD1J0GR
# 9	3WRBLBQ2GR6B7SGG6I11I6HFD1J0GR
# 10	3WRBLBQ2GR6B7SGG6I11I6HFD1J0GR
# 11	3MIVREZQVHW4X7HYD7GVV40QXMXQKH
# 12	3MIVREZQVHW4X7HYD7GVV40QXMXQKH
# 13	3MIVREZQVHW4X7HYD7GVV40QXMXQKH
# 14	3MIVREZQVHW4X7HYD7GVV40QXMXQKH
# 15	3MIVREZQVHW4X7HYD7GVV40QXMXQKH
# 16	3B286OTISEFHZ74Z6QJX4PL8EFCAJW
# 17	3B286OTISEFHZ74Z6QJX4PL8EFCAJW
# 18	3B286OTISEFHZ74Z6QJX4PL8EFCAJW
# 19	3B286OTISEFHZ74Z6QJX4PL8EFCAJW
# 20	39N6W9XWRDL84NC1EQCAAYBZPEXYGP
# 21	39N6W9XWRDL84NC1EQCAAYBZPEXYGP
# 22	39N6W9XWRDL84NC1EQCAAYBZPEXYGP
# 23	39N6W9XWRDL84NC1EQCAAYBZPEXYGP
# 24	39N6W9XWRDL84NC1EQCAAYBZPEXYGP
# 25	39N6W9XWRDL84NC1EQCAAYBZPEXYGP
# 26	3TL87MO8CMNIQO97KRH2Y59RFKUFLG
# 27	3TL87MO8CMNIQO97KRH2Y59RFKUFLG
# 28	3TL87MO8CMNIQO97KRH2Y59RFKUFLG
# 29	3TL87MO8CMNIQO97KRH2Y59RFKUFLG
# 30	3TL87MO8CMNIQO97KRH2Y59RFKUFLG
# 31	3TL87MO8CMNIQO97KRH2Y59RFKUFLG
# 32	3TL87MO8CMNIQO97KRH2Y59RFKUFLG
# 33	3DW3BNF1GHGC7EBEQHD2BMQ7JEJ8VB
# 34	3DW3BNF1GHGC7EBEQHD2BMQ7JEJ8VB
# 35	3DW3BNF1GHGC7EBEQHD2BMQ7JEJ8VB
# 36	3DW3BNF1GHGC7EBEQHD2BMQ7JEJ8VB
# 37	3DW3BNF1GHGC7EBEQHD2BMQ7JEJ8VB
# 38	3DW3BNF1GHGC7EBEQHD2BMQ7JEJ8VB
# 39	3DW3BNF1GHGC7EBEQHD2BMQ7JEJ8VB
# 40	3BO3NEOQM0FL4WKTO8YXSO6810NAIK
# 41	3BO3NEOQM0FL4WKTO8YXSO6810NAIK
# 42	3BO3NEOQM0FL4WKTO8YXSO6810NAIK
# 43	3BO3NEOQM0FL4WKTO8YXSO6810NAIK
# 44	3BO3NEOQM0FL4WKTO8YXSO6810NAIK
# 45	3BO3NEOQM0FL4WKTO8YXSO6810NAIK
# 46	3EPG8DX9LKOGFCVG67X0TARYV0H5PL
# 47	3EPG8DX9LKOGFCVG67X0TARYV0H5PL
# 48	3EPG8DX9LKOGFCVG67X0TARYV0H5PL
# 49	3EPG8DX9LKOGFCVG67X0TARYV0H5PL
# 50	3EPG8DX9LKOGFCVG67X0TARYV0H5PL
# 51	3EPG8DX9LKOGFCVG67X0TARYV0H5PL

# dtype: object

"""2. **[3 points]** Write the method `get_workerId_by_row` that returns the Worker ID at the given row in the dataframe."""

def get_workerId_by_row(df, row):
  return df['WorkerId'][row]
get_workerId_by_row(df, 3)

# EXAMPLE
# get_workerId_by_row(df, 3)
# 'A98E8M4QLI9RS'

"""3. **[5 points]** In the method `format_date` convert a datetime string from the format Year-Month-Day Hour-Minute-Second to a timestamp in minutes."""

# TODO
# convert the given date into a timestamp (in seconds)
from datetime import datetime
def format_date(date):
  dt = datetime.strptime(date, '%Y-%m-%d %H:%M:%S')
  dt0 = datetime(1970,1,1)
  delta = dt - dt0
  return delta.total_seconds()/60
format_date('2020-02-06 23:25:41')

# EXAMPLE
# format_date('2020-02-06 23:25:41') -> 26350525.683333334

"""4. **[5 points]** Use the `format_date` method to convert each entry in `SubmitTime` and `AcceptTime` into a timestamp. In `convert_times` return the series you get by applying that method to each entry in the given column"""

# hint: look at the dataframe apply method
def convert_times(df, column):
  df[column] = df[column].apply(format_date)
  return df[column]

# comment these out before you submit
#df['SubmitTime'] = convert_times(df, 'SubmitTime')
#df['AcceptTime'] = convert_times(df, 'AcceptTime')
#df.head()

"""5. **[5 points]** In `get_work_time` figure out how long each worker spent on the batch. Return the series that is the total work time indexed by the worker id."""

# hint: look at the dataframe groupby function
def get_work_time(df):
  df['TimeDelta'] = df['SubmitTime'] - df['AcceptTime']
  x = df.groupby('WorkerId')['TimeDelta'].sum()
  return x

get_work_time(df)

# EXAMPLE
# Should be a series like
# Time
# Time

"""6. **[10 points]** As we talked about in class workers can use tools to accept batches of HITs at once and then work on them sequentially. We suspect some of the workers in this batch have been using such a tool and that their work times overestimate how long they actually spent working. Write a method to calculate how long each worker actually spent working.

Hint: try to think about a worker's accept and submit times would look like if they were doing this and any overlap you might be able to find.
"""

#def calculated_work_time(df):

# EXAMPLE
# Series should look the same as above but with different values for some workers

"""7. **[0 points]** Here we'll show you how you can plot the data you just looked at.

Comment all of this out before you submit.
"""

#plot_df = pd.DataFrame()

#plot_df['WorkTime'] = get_work_time(df)

#plot_df['CWorkTime'] = calculated_work_time(df)

#plot_df.plot(kind='bar')

"""### 5.2 A Simple Program to Read from the Web [14 points]

The cell below uses the Pandas library to read a table from the given web page (the Wikipedia information on films in the year 2010). The code loads this into a list of DataFrames called films_2010. We then pull the table at index 3, then do some simple data wrangling on top_films to set up the appropriate types.

Run the cells below.
"""

# CAUTION: comment this out before you submit!
#!pip install money-parser

import pandas as pd
from money_parser import price_dec

"""**TODO:** Read in a list of dataframes from the url https://en.wikipedia.org/wiki/2010_in_film

*Hint:* Check the pandas documentation
"""

import requests
def read_from_html(url):
  headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
  response = requests.get(url, headers=headers)
  return pd.read_html(response.text)

films_2010 = read_from_html('https://en.wikipedia.org/wiki/2010_in_film')
films_2010

"""**TODO:** Find the table titled "Highest-grossing films"

*Hint:* Click on the url, and do some digging! Check out "Developer Tools" for the underlying html code and check which  < table >  tag contains the desired data
"""

def get_film_data(df_list):
  return films_2010[2]

top_films = get_film_data(films_2010)
top_films

"""**TODO:** write a method that sets the 'Rank' column as the index"""

def set_index(df, column):
  df.set_index(column, inplace = True)
  return df

top_films_ranked = set_index(top_films, 'Rank')

top_films_ranked

"""**TODO:** write a function that creates a column named 'Revenue (millions)', where the revenue in millions (rounded to 2 decimal places) are to be stored.

*Hint:* We recommend you use the imported function from the 'money_parser' module (see above).
"""

top_films_ranked.loc[4, 'Worldwide gross'] = '$828,258,695'

def extract_revenue(df, column, name):
  df[name] = df[column].apply(lambda x: round(price_dec(x)/1_000_000, 2))
  return df

top_films_revenue = extract_revenue(top_films_ranked, 'Worldwide gross', 'Revenue (millions)')
top_films_revenue

"""Can we programmatically compute how many entries were scored as top films?

You can use the Python shape function on a dataframe to determine the dimensions!
To learn more about the shape function, you can search for its pandas documentation.

**TODO:** Create a function that calculates the shape of the final dataframe (top_films_revenue) and returns a tuple
"""

def get_dimensions(df):
  col = rows = 0
  for i in df.columns:
    col += 1
  for i in df.index:
    rows += 1
  return (rows, col)
get_dimensions(top_films_revenue)